services:
  auth-service:
    volumes:
      - ./auth-service:/auth-service
    develop:
      watch:
        - path: ./auth-service
          action: sync
          target: /auth-service
          ignore:
            - ./auth-service/.venv
        - path: ./auth-service/pyproject.toml
          action: rebuild

  auth-db:
    ports:
      - "5432:5432"
