name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    defaults:
      run:
        working-directory: auth-service

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13.3"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true

      - name: Install dependencies
        run: uv sync

      - name: Test and Coverage
        run: ENV_FILE=.env.example uv run pytest --cov=app --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: auth-service
          files: auth-service/coverage.xml
